services:
  - type: web
    name: spring-boot-neon-project
    env: java
    buildCommand: ./mvnw clean install -DskipTests
    startCommand: java -jar target/*.jar
    plan: free
    region: oregon  # or your nearest region
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://ep-damp-bush-adbwvibu-pooler.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require
      - key: SPRING_DATASOURCE_USERNAME
        value: neondb_owner
      - key: SPRING_DATASOURCE_PASSWORD
        value: npg_hfq4RprF8GMg
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
      - key: SPRING_JPA_SHOW_SQL
        value: true
